### ISSUE TITLE
Missing apply_bpe.py

### ISSUE THREAD

**Issue by hyeonseokk** [ZhenYangIACAS/WeTS#1]
Hi
I am trying to implement your code following the instruction you noted in README.md.
I found that "apply_bpe.py" which is required in executing "process.sh" does not exist in the repository.
Could you please provide more information about the subword tokenization method?

Additionally, I cannot find the sentencepiece model or BPE model that is suited to the pre-trained model you have released. Is there any released file that I have not found yet?

Thank you

**Comment by hyeonseokk** [comment]
Additionally, could you please provide more instructions about the "TOOLS_DIR=path_to_tools" that is included in inference bash files? What files should we compose in the "path_to_tools" directory for implementing these?

**Comment by ZhenYangIACAS** [comment]
@hyeonseokk Hi, sorry for late reply.  
  1 apply_bpe.py is the standard script of the toolkit subword-nmt, which can be accessed at https://github.com/rsennrich/subword-nmt.
  2 The bpe codes can be found in the directory nmt_dicts_{src_lang}_{tgt_lang}
  3 "TOOLS_DIR" is the directory which stores your toolkit, you can push any scripts you need into the tool directory. 
  Wish I have answered your questions. Feel free to contact us if you have any other questions.

**Comment by hyeonseokk** [comment]
@ZhenYangIACAS Thank you for your reply. I will try it following your instruction.
