### ISSUE TITLE
training dataset of pre-trained NMT models

### ISSUE THREAD

**Issue by tmtmaj** [ZhenYangIACAS/WeTS#3]
Hi, I'm trying to reproduce the baseline TS model.
I wonder what kind of data is the training data of the pre-trained NMT models.

**Comment by ZhenYangIACAS** [comment]
Hi, The NMT models for EN-De are trained with WMT14 English-German corpus. For Chinese-English, we use the WMT19 English-Chinese corpus and the same amout of in-house corpus.  All of the models are released and you can directly utilize the models we provide.
